version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        DOCKER_GID: 109  # Ensure this matches the host's docker group GID
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/workspace_data:/home/workspace_data  # ✅ Absolute path with proper permissions
    container_name: lamp_frontend

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

